<?php

namespace App\Http\Controllers;

use App\Models\Doctor;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Schema;

class DoctorController extends Controller
{
    public function index()
    {
        $doctors = Doctor::all();
        $first_doctor = Doctor::find(1);
        // $columns = Schema::getColumnListing('doctors');
        // foreach ($columns as $column) {
        //     echo $column . "\n";
        // }
        // Pass the doctors data to the index view
        return view('index', ['doctors' => $doctors,'first_doctor' => $first_doctor]);
    }

    public function submitForm(Request $request)
    {
        // Validate the form data
        $validatedData = $request->validate([
            'full_name' => 'required|string',
            'profession' => 'required|string',
            'hospital' => 'required|string',
            'sex' => 'required|in:M,F',
            'age' => 'required|integer',
        ]);

        // Update the doctor object with the form data
        $doctor = new Doctor();
        $doctor->full_name = $validatedData['full_name'];
        $doctor->profession = $validatedData['profession'];
        $doctor->hospital = $validatedData['hospital'];
        $doctor->sex = $validatedData['sex'];
        $doctor->age = $validatedData['age'];
        // Save the doctor to the database
        $doctor->save();
        // Flash old input to session, so the old function works correctly 
        $request->flash();

        // You can now save the $doctor object to the database or perform any other actions
        // return 'mmmm';
        // Assuming the form is successfully submitted
        $successMessage = "Form submitted successfully!";

        return redirect()->route('index')->with('formSuccess', $successMessage);
        // return redirect()->route('index')->with('success', 'Form submitted successfully!');
    }
    public function deleteAllDoctors()
    {
        // Delete all doctors from the database
        Doctor::truncate();
        // Assuming doctors are successfully deleted
        $deleteSuccessMessage = "All doctors deleted successfully!";

        return redirect()->route('index')->with('deleteSuccess', $deleteSuccessMessage);
        // return redirect()->route('index')->with('success', 'All doctors deleted successfully!');
    }
    public function addTwoDoctors()
    {
        // Create two doctor objects
        $doctor1 = new Doctor();
        $doctor1->full_name = 'John Doe';
        $doctor1->profession = 'Medic';
        $doctor1->hospital = 'City Hospital';
        $doctor1->sex = 'M';
        $doctor1->age = 35;
        $doctor1->save();

        $doctor2 = new Doctor();
        $doctor2->full_name = 'Alex Who';
        $doctor2->profession = 'Cardiologist';
        $doctor2->hospital = 'General Hospital';
        $doctor2->sex = 'F';
        $doctor2->age = 42;
        $doctor2->save();

        // Optionally, you can use a transaction to ensure that both doctors are saved or none
        // DB::transaction(function () use ($doctor1, $doctor2) {
        //     $doctor1->save();
        //     $doctor2->save();
        // });
    
        return redirect()->route('index')->with('success', 'Two doctors added successfully!');
    
    }
    public function records() {
        $doctors = Doctor::all();
        return view('records', ['doctors' => $doctors]);
    }
    // public function exportToExcel() {
    //     $doctors = Doctor::all();
    //     return view('records', ['doctors' => $doctors]);
    // }
    public function exportToExcel() {
    $doctors = Doctor::all();
    // return view('records', ['doctors' => $doctors]);
    
    // Prepare data to be passed to Python script
    $doctorsJson = json_encode($doctors);

    // Command to execute Python script
    // $command = "python export_to_excel.py '" . $doctorsJson . "'";
    $command = "python ~/laravel/myapp/export_to_excel.py '" . $doctorsJson . "'";
    // $command = "python ~/laravel/myapp/export_to_excel.py";
    
    // Execute the command
exec($command, $output, $return);

if ($return === 0) {
    // return response()->download('output.xlsx');
    return "yeeeeeeeeees";
} else {
    // Output the return code and any output generated by the Python script
    return "Error occurred while exporting to Excel. Return code: "
    . $return . ". Output: " . implode("\n", $output) .
     "<br> Command: " . $command;

}


}

}



